### ISSUE TITLE
deprecation warnings on Ember 2.4.2

### ISSUE THREAD

**Issue by bgentry** [imgix/ember-cli-imgix#12]
Seeing these when using an `imgix-image` component on an Ember 2.4.2 app:

```
DEPRECATION: Using the injected `container` is deprecated. Please use the `getOwner` helper instead to access the owner of this object. [deprecation id: ember-application.injected-container] See http://emberjs.com/deprecations/v2.x#toc_injected-container-access for more details.
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16376:7)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:16286:12)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16376:7)
        at invoke (http://localhost:4200/assets/vendor.js:16392:7)
        at deprecate (http://localhost:4200/assets/vendor.js:16345:32)
        at Object.deprecate (http://localhost:4200/assets/vendor.js:26461:37)
        at Object.defineProperty.get (http://localhost:4200/assets/vendor.js:11582:26)
        at .<anonymous> (http://localhost:4200/assets/vendor.js:131841:18)
        at Descriptor.ComputedPropertyPrototype.get (http://localhost:4200/assets/vendor.js:25263:28)
ember.debug.js:6208 DEPRECATION: A property of <myapp-ember@view:-outlet::ember611> was modified inside the didInsertElement hook. You should never change properties on components, services or models during didInsertElement because it causes significant performance degradation. [deprecation id: ember-views.dispatching-modify-property]
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16376:7)
        at raiseOnDeprecation (http://localhost:4200/assets/vendor.js:16286:12)
        at HANDLERS.(anonymous function) (http://localhost:4200/assets/vendor.js:16376:7)
        at invoke (http://localhost:4200/assets/vendor.js:16392:7)
        at deprecate (http://localhost:4200/assets/vendor.js:16345:32)
        at Object.deprecate (http://localhost:4200/assets/vendor.js:26461:37)
        at exports.default._emberMetalMixin.Mixin.create._Mixin$create.scheduleRevalidate (http://localhost:4200/assets/vendor.js:53421:22)
        at http://localhost:4200/assets/vendor.js:23840:32
        at Object.BasicStream.notifySubscribers (http://localhost:4200/assets/vendor.js:32430:11)
```

**Comment by kellysutton** [comment]
Thanks for bringing this up. Looks like the problem code is here: https://github.com/imgix/ember-cli-imgix/blob/master/addon/mixins/imgix-path-behavior.js#L208-L210

We'll review and see what the path forward here is. Likely just need to update the addon to take advantage of more public APIs.

**Comment by reidab** [comment]
The second deprecation warning about modifying properties within `didInsertElement` points to a legitimate performance concern. We've been experiencing browser crashes when moving between pages of collections containing many `imgix-image` components. Deferring the resize count update with `Ember.run.once` seems to solve the issue. PR incoming…
