### ISSUE TITLE
latest release fails after install due to missing URI.js dependency

### ISSUE THREAD

**Issue by bgentry** [imgix/ember-cli-imgix#9]
Hi there. I ran `ember install ember-cli-imgix` on a new Ember app. However, now `ember serve` fails with the following trace:

```
✗ ember serve
version: 2.4.2
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [SourceMapConcat: Concat: Vendor /assets/vendor.js] failed with:
Error: ENOENT: no such file or directory, stat '/Users/bgentry/Code/myapp-ember/tmp/source_map_concat-input_base_path-2TiuraMf.tmp/0/bower_components/uri.js/src/URI.js'
    at Error (native)
    at Object.fs.statSync (fs.js:844:18)
    at ConcatWithMaps.keyForFile (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:112:65)
    at /Users/bgentry/Code/myapp-ember/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)

The broccoli plugin was instantiated at: 
    at ConcatWithMaps.Plugin (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/index.js:10:31)
    at ConcatWithMaps.CachingWriter [as constructor] (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/node_modules/broccoli-concat/node_modules/broccoli-caching-writer/index.js:21:10)
    at new ConcatWithMaps (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/node_modules/broccoli-concat/concat.js:22:17)
    at module.exports (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/node_modules/broccoli-concat/index.js:26:10)
    at EmberApp.concatFiles (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:329:10)
    at EmberApp.javascript (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:1190:12)
    at EmberApp.toArray (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:1542:10)
    at EmberApp.toTree (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/lib/broccoli/ember-app.js:1564:30)
    at module.exports (/Users/bgentry/Code/myapp-ember/ember-cli-build.js:22:14)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/bgentry/Code/myapp-ember/node_modules/ember-cli/lib/models/builder.js:55:19)
```

I was able to get things working via the following steps:

* `bower install uri.js` (actually installs as `urijs`)
* `mv bower_compenents/urijs bower_components/uri.js

I believe the cause is that the uri.js bower package renamed to urijs recently. I have a PR incoming that should fix this.

**Comment by paulstraw** [comment]
Thanks @bgentry. This is released as 0.2.1. :grin:

**Comment by bgentry** [comment]
@paulstraw are you planning to cut a new release on npm? It still shows 0.2.0

**Comment by paulstraw** [comment]
Whoops! Should be published now. Thanks!

**Comment by bgentry** [comment]
so this may not actually be resolved after all. Even on the latest version, I had to `bower install --save urljs` after installing the addon to get that dependency. Seems that will need to be added as a separate bower dependency during install since it's only used by this addon (and not imgix-core-js).

**Comment by paulstraw** [comment]
Strange. Can you send through your bower.json? I haven't seen this problem before, and I'm not exactly sure what would be causing it in your case.

**Comment by bgentry** [comment]
bower.json before `ember install ember-cli-imgix`:

```json
{
  "name": "imgdrop-ember",
  "dependencies": {
    "ember": "~2.4.1",
    "ember-cli-shims": "0.1.0",
    "ember-cli-test-loader": "0.2.2",
    "ember-qunit-notifications": "0.1.0",
    "pretender": "~0.10.1",
    "lodash": "~3.7.0",
    "Faker": "~3.0.0"
  }
}
```

and after:

```json
{
  "name": "imgdrop-ember",
  "dependencies": {
    "ember": "~2.4.1",
    "ember-cli-shims": "0.1.0",
    "ember-cli-test-loader": "0.2.2",
    "ember-qunit-notifications": "0.1.0",
    "pretender": "~0.10.1",
    "lodash": "~3.7.0",
    "Faker": "~3.0.0",
    "imgix-core-js": "1.0.3"
  }
}
```

and one which actually builds:

```json
{
  "name": "imgdrop-ember",
  "dependencies": {
    "ember": "~2.4.1",
    "ember-cli-shims": "0.1.0",
    "ember-cli-test-loader": "0.2.2",
    "ember-qunit-notifications": "0.1.0",
    "pretender": "~0.10.1",
    "lodash": "~3.7.0",
    "Faker": "~3.0.0",
    "imgix-core-js": "1.0.3",
    "urijs": "^1.17.1"
  }
}
```

**Comment by paulstraw** [comment]
Hmm, In your second and third examples, I'm only seeing `imgix-core-js`, not `ember-cli-imgix`…. Am I missing something?

**Comment by bgentry** [comment]
Seems that only goes into package.json

**Comment by paulstraw** [comment]
Ah, I missed the `ember` in `ember install`. Can you give the `9-ember-install-fix` branch from https://github.com/imgix/ember-cli-imgix/pull/11 a shot and let me know if it works for you?

**Comment by bgentry** [comment]
yep, that fixes it.

**Comment by paulstraw** [comment]
Alright @bgentry, 0.2.2 should have this all working now.

**Comment by bgentry** [comment]
works great, thanks! :v:
